[package]
name = "fsdb"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.84"
libc = "0.2.169"
nix = { version = "0.29.0", features = ["aio", "fs"] }
tokio = { version = "1.42.0", features = ["full", "mio"] }
